name: docgen

on:
  workflow_call:
    inputs:
      project-name:
        description: The name of the project
        required: true
        type: string
      node-version:
        description: The version of Node.js to use. Defaults to Node 20
        required: false
        default: 20
        type: number
      operating-system:
        description: The operating system to use
        required: false
        default: ubuntu-latest
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  docgen:
    name: Build Documentation
    runs-on: ${{ inputs.operating-system }}
    if: github.repository_owner == 'sapphiredev'
    outputs:
      NAME: ${{ steps.env.outputs.NAME }}
      TYPE: ${{ steps.env.outputs.TYPE }}
      SHA: ${{ steps.env.outputs.SHA }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: sapphiredev/.github/actions/install-yarn-dependencies@main
        with:
          node-version: ${{ inputs.node-version }}
      - name: Build Documentation
        run: yarn docs
      - name: Upload Documentation Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/api.json
      - name: Set Output
        id: env
        run: |
          echo "NAME=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          echo "TYPE=${GITHUB_REF_TYPE}" >> $GITHUB_OUTPUT
          echo "SHA=${GITHUB_SHA}" >> $GITHUB_OUTPUT

  upload:
    name: Upload Documentation
    needs: docgen
    runs-on: ${{ inputs.operating-system}}
    env:
      NAME: ${{ needs.docgen.outputs.NAME }}
      TYPE: ${{ needs.docgen.outputs.TYPE }}
      SHA: ${{ needs.docgen.outputs.SHA }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: sapphiredev/.github/actions/install-yarn-dependencies@main
        with:
          node-version: ${{ inputs.node-version }}
      - name: Download Documentation Artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs
      - name: Checkout Documentation Project
        uses: actions/checkout@v4
        with:
          repository: 'sapphiredev/docs'
          token: ${{ secrets.SKYRA_TOKEN }}
          path: 'out'

      - name: Move Documentation
        if: ${{ env.TYPE == 'tag' }}
        env:
          SEMVER: ${{ env.NAME }}
        run: |
          mkdir -p out/${{ inputs.project-name }}
          mv docs/api.json out/docs/${{ inputs.project-name }}/${SEMVER}.json
      - name: Move Documentation
        if: ${{ env.TYPE == 'branch' }}
        run: |
          mkdir -p out/${{ inputs.project-name }}
          mv docs/api.json out/docs/${{ inputs.project-name }}/${NAME}.json

      - name: Commit & Push
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 1
          command: |
            cd out
            git add .
            if git diff-index --quiet HEAD --; then
              echo "No changes to commit, exiting with code 0"
              exit 0;
            else
              git config user.name github-actions[bot]
              git config user.email 41898282+github-actions[bot]@users.noreply.github.com
              git config rebase.autostash true
              git config pull.rebase true
              git commit -m "docs(${{ inputs.project-name }}): build for ${TYPE} ${NAME}: ${SHA}" || true
              git pull
              git push
            fi
