name: prettier

on:
  workflow_call:
    inputs:
      node-version:
        description: The version of Node.js to use
        required: false
        default: 20
        type: number
      operating-system:
        description: The operating system to use
        required: false
        default: ubuntu-latest
        type: string

jobs:
  prettier:
    name: Prettier checking
    uses: sapphiredev/.github/.github/workflows/reusable-yarn-job.yml@main
    with:
      script-name: format:check
      operating-system: ${{ inputs.operating-system }}
      node-version: ${{ inputs.node-version }}
