name: Check Prettier

on:
  workflow_call:
    inputs:
      node-version:
        description: The version of Node.js to use
        required: false
        default: 20
        type: number
      operating-system:
        description: The operating system to use
        required: false
        default: ubuntu-latest
        type: string

jobs:
  check:
    name: Check Prettier
    runs-on: ${{ inputs.operating-system }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: sapphiredev/.github/actions/install-yarn-dependencies
        with:
          node-version: ${{ inputs.node-version }}
      - name: Run Prettier
        run: yarn format:check
