name: Check Prettier

on:
  workflow_call:
    inputs:
      node-version:
        description: The version of Node.js to use
        required: false
        default: 20
        type: number
      operating-system:
        description: The operating system to use
        required: false
        default: ubuntu-latest
        type: string

jobs:
  check:
    name: Check Prettier
    runs-on: ${{ inputs.operating-system }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Checkout CI repository
        uses: actions/checkout@v4
        with:
          path: ci-actions
          sparse-checkout: actions/
          sparse-checkout-cone-mode: false
          repository: sapphiredev/.github
      - name: Install dependencies
        uses: ./ci-actions/actions/install-yarn-dependencies
        with:
          node-version: ${{ inputs.node-version }}
      - name: Run Prettier
        run: yarn format:check
