name: docgen

on:
  workflow_call:
    inputs:
      node-version:
        description: The version of Node.js to use. Defaults to Node 20
        required: false
        default: 20
        type: number
      operating-system:
        description: The operating system to use
        required: false
        default: ubuntu-latest
        type: string
      mono-repo:
        description: Whether this targets a monorepo or not
        required: false
        default: true
        type: boolean

concurrency:
  group: documentation|${{ github.head_ref || github.ref }}|${{ inputs.operating-system }}|${{ inputs.node-version }}
  cancel-in-progress: true

jobs:
  docgen:
    name: Build Documentation
    runs-on: ${{ inputs.operating-system }}
    if: github.repository_owner == 'sapphiredev'
    outputs:
      NAME: ${{ steps.env.outputs.NAME }}
      TYPE: ${{ steps.env.outputs.TYPE }}
      SHA: ${{ steps.env.outputs.SHA }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: sapphiredev/.github/actions/install-yarn-dependencies@main
        with:
          node-version: ${{ inputs.node-version }}
      - name: Build Documentation
        run: yarn docs
      - name: Upload Documentation Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: ${{ inputs.mono-repo == true && 'packages/*/docs/api.json' || 'docs/api.json' }}
      - name: Set Output
        id: env
        run: |
          echo "NAME=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          echo "TYPE=${GITHUB_REF_TYPE}" >> $GITHUB_OUTPUT
          echo "SHA=${GITHUB_SHA}" >> $GITHUB_OUTPUT
